name: Android CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 21
          cache: gradle

      # 3. Делаем gradlew исполняемым
      - name: Grant execute permission for gradlew
        run: chmod +x gradlew
        
      #- name: Run Spotless check
      #  run: ./gradlew spotlessCheck

      - name: Build with Gradle
        run: ./gradlew build --stacktrace

      #- name: Run unit tests
      #  run: ./gradlew test
      - name: Assemble Debug APK
        run: ./gradlew assembleDebug

      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: app-debug
          path: app/build/outputs/apk/debug/app-debug.apk
